"""Extra Allegro category URLs — merged into allegro_scraper.ALLEGRO_CATEGORIES."""

ALLEGRO_EXTRA_CATEGORIES = [
    {"url": "https://allegro.pl/kategoria/telewizory-257699", "category_id": "tv-audio", "path": ["Electronics", "TV & Audio", "TV"]},
    {"url": "https://allegro.pl/kategoria/monitory-488", "category_id": "computers", "path": ["Electronics", "Computers", "Monitors"]},
    {"url": "https://allegro.pl/kategoria/drukarki-i-skanery-492", "category_id": "computers", "path": ["Electronics", "Computers", "Printers"]},
    {"url": "https://allegro.pl/kategoria/komputery-stacjonarne-486", "category_id": "computers", "path": ["Electronics", "Computers", "Desktop"]},
    {"url": "https://allegro.pl/kategoria/karty-graficzne-260425", "category_id": "computers", "path": ["Electronics", "Computers", "GPU"]},
    {"url": "https://allegro.pl/kategoria/procesory-260422", "category_id": "computers", "path": ["Electronics", "Computers", "CPU"]},
    {"url": "https://allegro.pl/kategoria/pamieci-ram-260423", "category_id": "computers", "path": ["Electronics", "Computers", "RAM"]},
    {"url": "https://allegro.pl/kategoria/dyski-ssd-260424", "category_id": "computers", "path": ["Electronics", "Computers", "SSD"]},
    {"url": "https://allegro.pl/kategoria/routery-260426", "category_id": "computers", "path": ["Electronics", "Computers", "Routers"]},
    {"url": "https://allegro.pl/kategoria/myszki-4574", "category_id": "computers", "path": ["Electronics", "Computers", "Mice"]},
    {"url": "https://allegro.pl/kategoria/klawiatury-4575", "category_id": "computers", "path": ["Electronics", "Computers", "Keyboards"]},
    {"url": "https://allegro.pl/kategoria/aparaty-cyfrowe-447902", "category_id": "cameras", "path": ["Electronics", "Cameras"]},
    {"url": "https://allegro.pl/kategoria/glosniki-257700", "category_id": "speakers", "path": ["Electronics", "TV & Audio", "Speakers"]},
    {"url": "https://allegro.pl/kategoria/gry-na-konsole-256086", "category_id": "games", "path": ["Gaming", "Games"]},
    {"url": "https://allegro.pl/kategoria/akcesoria-do-konsol-256087", "category_id": "gaming-accessories", "path": ["Gaming", "Accessories"]},
    {"url": "https://allegro.pl/kategoria/laptopy-do-gier-491", "category_id": "gaming-laptops", "path": ["Gaming", "Laptops"]},
    {"url": "https://allegro.pl/kategoria/pralki-214", "category_id": "appliances", "path": ["Home & Garden", "Appliances"]},
    {"url": "https://allegro.pl/kategoria/lodowki-215", "category_id": "appliances", "path": ["Home & Garden", "Appliances"]},
    {"url": "https://allegro.pl/kategoria/zmywarki-216", "category_id": "appliances", "path": ["Home & Garden", "Appliances"]},
    {"url": "https://allegro.pl/kategoria/roboty-kuchenne-552", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen"]},
    {"url": "https://allegro.pl/kategoria/ekspresy-do-kawy-553", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen"]},
    {"url": "https://allegro.pl/kategoria/buty-sportowe-damskie-532", "category_id": "sneakers", "path": ["Fashion", "Shoes", "Women"]},
    {"url": "https://allegro.pl/kategoria/zegarki-meskie-257931", "category_id": "jewelry", "path": ["Fashion", "Watches"]},
    {"url": "https://allegro.pl/kategoria/rowery-257873", "category_id": "cycling", "path": ["Sports & Tourism", "Cycling"]},
    {"url": "https://allegro.pl/kategoria/hulajnogi-elektryczne-257874", "category_id": "outdoor", "path": ["Sports & Tourism", "Outdoor"]},
    {"url": "https://allegro.pl/kategoria/perfumy-meskie-261321", "category_id": "perfume", "path": ["Beauty", "Perfume"]},
    {"url": "https://allegro.pl/kategoria/klocki-257872", "category_id": "kids", "path": ["Kids", "Blocks"]},
    {"url": "https://allegro.pl/kategoria/opony-letnie-257875", "category_id": "automotive", "path": ["Automotive", "Tyres"]},
]
