"""Extra Ceneo.pl listing URLs — merged into ceneo_scraper.CENEO_CATEGORIES. category_id must exist in seed_categories."""

CENEO_EXTRA_CATEGORIES = [
    # Electronics / computers
    {"url": "https://www.ceneo.pl/Karty_graficzne", "category_id": "computers", "path": ["Electronics", "Computers", "Graphics"]},
    {"url": "https://www.ceneo.pl/Procesory", "category_id": "computers", "path": ["Electronics", "Computers", "CPU"]},
    {"url": "https://www.ceneo.pl/Plyty_glowne", "category_id": "computers", "path": ["Electronics", "Computers", "Motherboards"]},
    {"url": "https://www.ceneo.pl/Pamieci_RAM", "category_id": "computers", "path": ["Electronics", "Computers", "RAM"]},
    {"url": "https://www.ceneo.pl/Dyski_SSD", "category_id": "computers", "path": ["Electronics", "Computers", "SSD"]},
    {"url": "https://www.ceneo.pl/Dyski_twarde", "category_id": "computers", "path": ["Electronics", "Computers", "HDD"]},
    {"url": "https://www.ceneo.pl/Obudowy_komputerowe", "category_id": "computers", "path": ["Electronics", "Computers", "Cases"]},
    {"url": "https://www.ceneo.pl/Zasilacze_komputerowe", "category_id": "computers", "path": ["Electronics", "Computers", "PSU"]},
    {"url": "https://www.ceneo.pl/Chlodzenie_procesora", "category_id": "computers", "path": ["Electronics", "Computers", "Cooling"]},
    {"url": "https://www.ceneo.pl/Routery", "category_id": "computers", "path": ["Electronics", "Computers", "Routers"]},
    {"url": "https://www.ceneo.pl/Myszki", "category_id": "computers", "path": ["Electronics", "Computers", "Mice"]},
    {"url": "https://www.ceneo.pl/Klawiatury", "category_id": "computers", "path": ["Electronics", "Computers", "Keyboards"]},
    {"url": "https://www.ceneo.pl/Kamery_internetowe", "category_id": "cameras", "path": ["Electronics", "Cameras", "Webcams"]},
    {"url": "https://www.ceneo.pl/Kamery_sportowe", "category_id": "cameras", "path": ["Electronics", "Cameras", "Action"]},
    {"url": "https://www.ceneo.pl/Obiektywy", "category_id": "cameras", "path": ["Electronics", "Cameras", "Lenses"]},
    {"url": "https://www.ceneo.pl/Telefony_komorkowe", "category_id": "phones", "path": ["Electronics", "Phones"]},
    {"url": "https://www.ceneo.pl/Etui_do_telefonow", "category_id": "accessories-electronics", "path": ["Electronics", "Accessories", "Cases"]},
    {"url": "https://www.ceneo.pl/Powerbanki", "category_id": "accessories-electronics", "path": ["Electronics", "Accessories", "Powerbanks"]},
    {"url": "https://www.ceneo.pl/Kable", "category_id": "accessories-electronics", "path": ["Electronics", "Accessories", "Cables"]},
    {"url": "https://www.ceneo.pl/Adaptery", "category_id": "accessories-electronics", "path": ["Electronics", "Accessories", "Adapters"]},
    {"url": "https://www.ceneo.pl/Soundbary", "category_id": "tv-audio", "path": ["Electronics", "TV & Audio", "Soundbars"]},
    {"url": "https://www.ceneo.pl/Projektory", "category_id": "tv-audio", "path": ["Electronics", "TV & Audio", "Projectors"]},
    {"url": "https://www.ceneo.pl/Odtwarzacze_Blu_ray", "category_id": "tv-audio", "path": ["Electronics", "TV & Audio", "Blu-ray"]},
    # Home
    {"url": "https://www.ceneo.pl/Chlodnictwo", "category_id": "appliances", "path": ["Home & Garden", "Appliances", "Fridges"]},
    {"url": "https://www.ceneo.pl/Zamrazarki", "category_id": "appliances", "path": ["Home & Garden", "Appliances", "Freezers"]},
    {"url": "https://www.ceneo.pl/Mikrofalowki", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen", "Microwaves"]},
    {"url": "https://www.ceneo.pl/Plyty_indukcyjne", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen", "Induction"]},
    {"url": "https://www.ceneo.pl/Okapy_kuchenne", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen", "Hoods"]},
    {"url": "https://www.ceneo.pl/Zlewozmywaki", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen", "Sinks"]},
    {"url": "https://www.ceneo.pl/Baterie_kuchenne", "category_id": "kitchen", "path": ["Home & Garden", "Kitchen", "Taps"]},
    {"url": "https://www.ceneo.pl/Suszarki_do_ubran", "category_id": "appliances", "path": ["Home & Garden", "Appliances", "Dryers"]},
    {"url": "https://www.ceneo.pl/Zelazka", "category_id": "appliances", "path": ["Home & Garden", "Appliances", "Irons"]},
    {"url": "https://www.ceneo.pl/Odkurzacze_pionowe", "category_id": "appliances", "path": ["Home & Garden", "Appliances", "Stick vacuums"]},
    {"url": "https://www.ceneo.pl/Roboty_sprzatajace", "category_id": "appliances", "path": ["Home & Garden", "Appliances", "Robots"]},
    {"url": "https://www.ceneo.pl/Kosiarki", "category_id": "garden", "path": ["Home & Garden", "Garden", "Mowers"]},
    {"url": "https://www.ceneo.pl/Grille", "category_id": "garden", "path": ["Home & Garden", "Garden", "Grills"]},
    {"url": "https://www.ceneo.pl/Hustawki_ogrodowe", "category_id": "garden", "path": ["Home & Garden", "Garden", "Swings"]},
    {"url": "https://www.ceneo.pl/Lampy_zewnetrzne", "category_id": "lighting", "path": ["Home & Garden", "Lighting", "Outdoor"]},
    {"url": "https://www.ceneo.pl/Lampy_sufitowe", "category_id": "lighting", "path": ["Home & Garden", "Lighting", "Ceiling"]},
    # Fashion
    {"url": "https://www.ceneo.pl/Buty_sportowe_damskie", "category_id": "sneakers", "path": ["Fashion", "Shoes", "Women"]},
    {"url": "https://www.ceneo.pl/Kurtki_meskie", "category_id": "mens-clothing", "path": ["Fashion", "Men", "Jackets"]},
    {"url": "https://www.ceneo.pl/Kurtki_damskie", "category_id": "womens-clothing", "path": ["Fashion", "Women", "Jackets"]},
    {"url": "https://www.ceneo.pl/Spodnie_meskie", "category_id": "mens-clothing", "path": ["Fashion", "Men", "Trousers"]},
    {"url": "https://www.ceneo.pl/Sukienki", "category_id": "womens-clothing", "path": ["Fashion", "Women", "Dresses"]},
    {"url": "https://www.ceneo.pl/Portfele", "category_id": "bags", "path": ["Fashion", "Bags", "Wallets"]},
    {"url": "https://www.ceneo.pl/Plecaki", "category_id": "bags", "path": ["Fashion", "Bags", "Backpacks"]},
    # Beauty
    {"url": "https://www.ceneo.pl/Szczoteczki_elektryczne", "category_id": "skincare", "path": ["Beauty", "Care", "Electric toothbrushes"]},
    {"url": "https://www.ceneo.pl/Golarki", "category_id": "skincare", "path": ["Beauty", "Care", "Shavers"]},
    {"url": "https://www.ceneo.pl/Lakiery_do_paznokci", "category_id": "makeup", "path": ["Beauty", "Makeup", "Nails"]},
    {"url": "https://www.ceneo.pl/Tusze_do_rzes", "category_id": "makeup", "path": ["Beauty", "Makeup", "Mascara"]},
    # Sports
    {"url": "https://www.ceneo.pl/Hantle", "category_id": "fitness", "path": ["Sports & Tourism", "Fitness", "Dumbbells"]},
    {"url": "https://www.ceneo.pl/Maty_do_jogi", "category_id": "fitness", "path": ["Sports & Tourism", "Fitness", "Yoga"]},
    {"url": "https://www.ceneo.pl/Narty", "category_id": "outdoor", "path": ["Sports & Tourism", "Outdoor", "Skis"]},
    {"url": "https://www.ceneo.pl/Kaski_narciarskie", "category_id": "outdoor", "path": ["Sports & Tourism", "Outdoor", "Helmets"]},
    {"url": "https://www.ceneo.pl/Plecaki_turystyczne", "category_id": "outdoor", "path": ["Sports & Tourism", "Outdoor", "Backpacks"]},
    # Gaming extras
    {"url": "https://www.ceneo.pl/Kontrolery_do_konsol", "category_id": "gaming-accessories", "path": ["Gaming", "Accessories", "Controllers"]},
    {"url": "https://www.ceneo.pl/Gry_komputerowe", "category_id": "games", "path": ["Gaming", "Games", "PC"]},
    {"url": "https://www.ceneo.pl/Monitory_dla_graczy", "category_id": "gaming-laptops", "path": ["Gaming", "Monitors"]},
    # Kids / health / auto
    {"url": "https://www.ceneo.pl/Foteliki_samochodowe", "category_id": "kids", "path": ["Kids", "Car seats"]},
    {"url": "https://www.ceneo.pl/Zabawki", "category_id": "kids", "path": ["Kids", "Toys"]},
    {"url": "https://www.ceneo.pl/Termometry", "category_id": "health", "path": ["Health", "Thermometers"]},
    {"url": "https://www.ceneo.pl/Inhalatory", "category_id": "health", "path": ["Health", "Nebulizers"]},
    {"url": "https://www.ceneo.pl/Akumulatory", "category_id": "automotive", "path": ["Automotive", "Batteries"]},
    {"url": "https://www.ceneo.pl/Opony_zimowe", "category_id": "automotive", "path": ["Automotive", "Winter tyres"]},
    {"url": "https://www.ceneo.pl/Oleje_silnikowe", "category_id": "automotive", "path": ["Automotive", "Engine oil"]},
]
